# This is a minimal wrapper around ci.sh
# ci.sh is intended to be usable locally without github.

# This yaml file can be debugged using act https://github.com/nektos/act

name: ci
on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target_ci
          key: rust3-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}

      - name: build
        run: ./testing/ci.sh

      - name: picow bloat
        uses: actions/upload-artifact@v4
        with:
          name: picow-bloat
          path: ci_out/picow-bloat.txt
