# This is a minimal wrapper around ci.sh
# ci.sh is intended to be usable locally without github.
name: ci
on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust files
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            testing/target
          # Save a unique cache each time
          # (https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache)
          key: rust-cache1-${{ github.run_id }}
          # Load from the most recent match
          restore-keys: |
            rust-cache1

      - name: build
        run: ./testing/ci.sh

      - name: picow bloat
        uses: actions/upload-artifact@v4
        with:
          name: picow-bloat
          path: ci_out/picow-bloat.txt
